# Generated by Django 2.1.2 on 2019-01-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190126_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='images',
            field=models.ImageField(default='images?default.png', upload_to='images', verbose_name='头像'),
        ),
    ]
