# Generated by Django 2.1.2 on 2019-01-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190126_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='images',
            field=models.ImageField(default='images/default.gif', upload_to='images', verbose_name='头像'),
        ),
    ]
