# Generated by Django 2.1.2 on 2019-01-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190126_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.CharField(default='image/default.gif', max_length=100, verbose_name='头像'),
        ),
    ]
