# Generated by Django 2.1.2 on 2019-01-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190126_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='images',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.CharField(default='images/default.gif', max_length=100, verbose_name='头像'),
        ),
    ]
