# Generated by Django 2.1.2 on 2019-01-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190126_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.CharField(default='apps/users/static/users/images/default.gif', max_length=100, verbose_name='头像'),
        ),
    ]
