# Generated by Django 2.1.2 on 2019-02-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190222_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.CharField(default='/static/images/default.gif', max_length=100, verbose_name='头像'),
        ),
    ]
