#!/usr/bin/env bash

startNeo4j(){
    neo4j=$(ps -fe | grep neo4j | grep -v grep)
    if [[ $? -ne 0 ]];then
        neo4j start
        echo "neo4j启动完成！"
    else
        echo "neo4j运行中..."
    fi
}

startNginx(){
    nginx=$(ps -fe | grep nginx | grep -v grep)
    if [[ $? -ne 0 ]];then
        nginx
        echo "nginx启动完成！"
    else
        echo "nginx运行中..."
    fi
}

startUwsgi(){
    uwsgi=$(ps -fe | grep uwsgi | grep -v grep)
    if [[ $? -ne 0 ]];then
        cd "/root/MHKG/Django"
        uwsgi --ini uwsgi.ini
        echo "uwsgi启动完成！"
    else
        echo "uwsgi运行中..."
    fi
}

startSupervisord(){
    supervisord=$(ps ajx | grep supervisord | grep -v grep)
    if [[ $? -ne 0 ]];then
        supervisord -c /etc/supervisord.conf
        echo "supervisord启动完成！"
        startDaphne
    else
        echo "supervisord运行中..."
        startDaphne
    fi
}

startDaphne(){
    daphne=$(ps ajx | grep daphne | grep -v grep)
    if [[ $? -ne 0 ]];then
        supervisorctl start daphne
        echo "daphne启动完成！"
    else
        echo "daphne运行中..."
    fi
}

startProject(){
    startNeo4j
    startNginx
    startUwsgi
    startSupervisord
}

restartProject(){
    neo4j restart
    echo "neo4j重启完成"
    nginx -s reload
    echo "nginx重启完成"
    cd "/root/MHKG/Django/logs"
    uwsgi --stop uwsgi.pid
    sleep 1
    cd "/root/MHKG/Django"
    uwsgi --ini uwsgi.ini
    echo "uwsgi重启完成"
    supervisorctl restart daphne
    echo "daphne重启成功"
}

if [[ $# == 0 ]]; then
    startProject
elif [[ $# == 1 ]]; then
    NAME=$1
    if [[ ${NAME,,} == "start" ]]; then
        startProject
    elif [[ ${NAME,,} == "restart" ]]; then
        restartProject
    elif [[ ${NAME,,} == "status" ]]; then
        neo4j status
        echo "------"
        ps ajx | grep nginx
        echo "------"
        ps ajx | grep uwsgi
        echo "------"
        supervisorctl status
    else
        echo "命令错误"
    fi
else
    echo "命令错误"
fi
